// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Header {
    #[prost(uint32, tag = "1")]
    pub version: u32,
    /// H256
    #[prost(bytes = "vec", tag = "2")]
    pub prev_hash: ::prost::alloc::vec::Vec<u8>,
    /// H256
    #[prost(bytes = "vec", tag = "3")]
    pub merkle_root: ::prost::alloc::vec::Vec<u8>,
    /// i.e unix milliseconds
    #[prost(uint64, tag = "4")]
    pub timestamp: u64,
    #[prost(uint64, tag = "5")]
    pub nonce: u64,
    #[prost(uint32, tag = "6")]
    pub index: u32,
    #[prost(uint32, tag = "7")]
    pub primary_index: u32,
    /// H160
    #[prost(bytes = "vec", tag = "8")]
    pub next_consensus: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TrimmedBlock {
    #[prost(message, optional, tag = "1")]
    pub header: ::core::option::Option<Header>,
    /// H256 list, tx hash list
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub tx_hashes: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExtensiblePayload {
    #[prost(string, tag = "1")]
    pub category: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub valid_block_start: u32,
    #[prost(uint32, tag = "3")]
    pub valid_block_end: u32,
    /// H160
    #[prost(bytes = "vec", tag = "4")]
    pub sender: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "5")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccountSign {
    /// the signature
    #[prost(bytes = "vec", tag = "1")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    /// the compressed or uncompressed public key
    #[prost(bytes = "vec", tag = "2")]
    pub public_key: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccountContract {
    /// the contract script
    #[prost(bytes = "vec", tag = "1")]
    pub script: ::prost::alloc::vec::Vec<u8>,
    /// the contract parameters
    #[prost(uint32, repeated, tag = "2")]
    pub parameters: ::prost::alloc::vec::Vec<u32>,
    /// if the contract is deployed
    #[prost(bool, tag = "3")]
    pub deployed: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccountSigns {
    /// if the status is Single, there is only one sign
    /// if the status is Multiple, there are multiple signs
    /// if the status is NoSuchAccount, NoPrivateKey or Locked, there are no signs
    #[prost(message, repeated, tag = "1")]
    pub signs: ::prost::alloc::vec::Vec<AccountSign>,
    /// the account contract
    /// If the account hasn't a contract, the contract is null
    #[prost(message, optional, tag = "2")]
    pub contract: ::core::option::Option<AccountContract>,
    /// the account status
    #[prost(enumeration = "AccountStatus", tag = "3")]
    pub status: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MultiAccountSigns {
    #[prost(message, repeated, tag = "1")]
    pub signs: ::prost::alloc::vec::Vec<AccountSigns>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AccountStatus {
    /// / no such account
    NoSuchAccount = 0,
    /// / no private key
    NoPrivateKey = 1,
    /// / single sign
    Single = 2,
    /// / multiple signs, aka. multisig
    Multiple = 3,
    /// / this key-pair is locked
    Locked = 4,
}
impl AccountStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::NoSuchAccount => "NoSuchAccount",
            Self::NoPrivateKey => "NoPrivateKey",
            Self::Single => "Single",
            Self::Multiple => "Multiple",
            Self::Locked => "Locked",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NoSuchAccount" => Some(Self::NoSuchAccount),
            "NoPrivateKey" => Some(Self::NoPrivateKey),
            "Single" => Some(Self::Single),
            "Multiple" => Some(Self::Multiple),
            "Locked" => Some(Self::Locked),
            _ => None,
        }
    }
}
