// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ScriptHashSign {
    /// the signature
    #[prost(bytes = "vec", tag = "1")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    /// the compressed or uncompressed public key
    #[prost(bytes = "vec", tag = "2")]
    pub public_key: ::prost::alloc::vec::Vec<u8>,
    /// the account contract, empty if the account hasn't a contract
    #[prost(bytes = "vec", tag = "3")]
    pub contract: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ScriptHashSigns {
    /// if the status is Single, there is only one sign
    /// if the status is Multiple, there are multiple signs
    /// if the status is NoSuchAccount, NoPrivateKey or Locked, there are no signs
    #[prost(message, repeated, tag = "1")]
    pub signs: ::prost::alloc::vec::Vec<ScriptHashSign>,
    /// the account status
    #[prost(enumeration = "AccountStatus", tag = "2")]
    pub status: i32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AccountStatus {
    /// / no such account
    NoSuchAccount = 0,
    /// / no private key
    NoPrivateKey = 1,
    /// / single sign
    Single = 2,
    /// / multiple signs, aka. multisig
    Multiple = 3,
    /// / this key-pair is locked
    Locked = 4,
}
impl AccountStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::NoSuchAccount => "NoSuchAccount",
            Self::NoPrivateKey => "NoPrivateKey",
            Self::Single => "Single",
            Self::Multiple => "Multiple",
            Self::Locked => "Locked",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NoSuchAccount" => Some(Self::NoSuchAccount),
            "NoPrivateKey" => Some(Self::NoPrivateKey),
            "Single" => Some(Self::Single),
            "Multiple" => Some(Self::Multiple),
            "Locked" => Some(Self::Locked),
            _ => None,
        }
    }
}
